name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [docs-updated]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Get Repositories
        id: get-repos
        run: |
          echo "Fetching repositories from ops-frontier organization..."
          REPOS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/orgs/ops-frontier/repos?per_page=100" | jq -r '.[].name')
          echo "::set-output name=repos::$REPOS"

      - name: Download Docs Zips
        id: download-zips
        run: |
          mkdir -p docs-source
          for repo in ${{ steps.get-repos.outputs.repos }}; do
            echo "Processing repository: $repo"
            RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/ops-frontier/$repo/releases/latest")
            if [ $(echo "$RELEASE" | jq -r '.status') = "404" ]; then
              echo "No released asset"
            else
              ASSET_ID=$(echo "$RELEASE" | jq -r '.assets[] | select(.name == "docs.zip") | .id')
              if [ -n "$ASSET_ID" ]; then
                echo "Found docs.zip in $repo"
                curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" "https://api.github.com/repos/ops-frontier/$repo/releases/assets/$ASSET_ID" > docs-source/$repo.zip
                unzip -o docs-source/$repo.zip -d docs
                rm docs-source/$repo.zip
              else
                echo "docs.zip not found in $repo"
              fi
            fi
          done

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          